server:
  port: 8081

spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://config-server:8071/"
  cloud:
    consul:
      host: consul                 # Use the service name from docker-compose
      port: 8500                   # Consul's port
      discovery:
        service-name: product-service
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true
logstash:
  host: logstash   # Use the Docker service name (logstash) instead of localhost
  port: 5000       # Port where Logstash listens

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
  file:
    name: logs/product-ms.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"