server:
  port: 8081

spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    consul:
      discovery:
        service-name: product-service   # Register with Consul
        prefer-ip-address: true          # Use IP address for service discovery (important when running inside Docker).
        health-check-interval: 10s       # Check service health every 10 seconds
        health-check-path: /actuator/health  # Health check endpoint

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
