spring:
  application:
    name: product-service


server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - env
          - metrics
          - refresh
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
